[project]
name = "yfas"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "asyncio>=4.0.0",
    "curl-cffi>=0.13.0",
    "logging>=0.4.9.6",
]
