[project]
name = "yfas"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "asyncio>=4.0.0",
    "curl-cffi>=0.13.0",
    "logging>=0.4.9.6",
]

[tool.ruff]
line-length = 88
indent-width = 4

[tool.ruff.lint]
extend-select = ["E501", "N", "R", "I", "C901", "PD", "NPY", "D"]
ignore = ["D100", "D104", "D107"]

[tool.ruff.format]
quote-style = "single"
indent-style = "space"

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.mypy]
strict = true
explicit_package_bases = true
check_untyped_defs = true
disallow_untyped_calls = false
disable_error_code = ["no-any-return"]
