from typing import Any, Callable

from ._types import (
    AssetProfile,
    CalendarEvents,
    CalendarEventsResponseJson,
    ChartResponseJson,
    ChartResult,
    CurrenciesResponseJson,
    DefaultKeyStatistics,
    Earnings,
    EarningsHistoryItem,
    EarningsTrendItem,
    FinancialData,
    FundOwnershipItem,
    IndexTrend,
    IndustryTrend,
    InsiderHolderItem,
    InsiderTransactionItem,
    InsightsFinanceResult,
    InsightsResponseJson,
    InstitutionOwnershipItem,
    MajorDirectHolders,
    MajorHoldersBreakdown,
    MarketSummaryResponseJson,
    NetSharePurchaseActivity,
    OptionChainResult,
    OptionsResponseJson,
    PageViews,
    Price,
    QuoteResponseJson,
    QuoteResult,
    QuoteSummaryResponseJson,
    QuoteTypeResponseJson,
    QuoteTypeResult,
    RatingsResult,
    RecommendationsFinanceResult,
    RecommendationsResponseJson,
    RecommendationTrendItem,
    SecFilings,
    SectorTrend,
    SummaryDetail,
    SummaryProfile,
    TimeseriesResponseJson,
    TrendingResponseJson,
    UpgradeDowngradeHistoryItem,
)

_MODULE_MAP = {
    'assetProfile': AssetProfile,
    'recommendationTrend': list[RecommendationTrendItem],
    'indexTrend': IndexTrend,
    'defaultKeyStatistics': DefaultKeyStatistics,
    'industryTrend': IndustryTrend,
    'fundOwnership': list[FundOwnershipItem],
    'summaryDetail': SummaryDetail,
    'insiderHolders': list[InsiderHolderItem],
    'calendarEvents': CalendarEvents,
    'upgradeDowngradeHistory': list[UpgradeDowngradeHistoryItem],
    'price': Price,
    'earningsTrend': list[EarningsTrendItem],
    'secFilings': SecFilings,
    'institutionOwnership': list[InstitutionOwnershipItem],
    'majorHoldersBreakdown': MajorHoldersBreakdown,
    'earningsHistory': list[EarningsHistoryItem],
    'majorDirectHolders': MajorDirectHolders,
    'summaryProfile': SummaryProfile,
    'netSharePurchaseActivity': NetSharePurchaseActivity,
    'insiderTransactions': list[InsiderTransactionItem],
    'sectorTrend': SectorTrend,
    'earnings': Earnings,
    'pageViews': PageViews,
    'financialData': FinancialData,
}

_RESULT_KEY_MAP = {
    ChartResponseJson: 'chart',
    QuoteResponseJson: 'quoteResponse',
    QuoteTypeResponseJson: 'quoteType',
    QuoteSummaryResponseJson: 'quoteSummary',
    TimeseriesResponseJson: 'timeseries',
    OptionsResponseJson: 'optionChain',
    RecommendationsResponseJson: 'finance',
    InsightsResponseJson: 'finance',
    MarketSummaryResponseJson: 'marketSummaryResponse',
    TrendingResponseJson: 'finance',
    CurrenciesResponseJson: 'currencies',
    CalendarEventsResponseJson: 'finance',
}

_PARSE_TICKER_FUNCS_MAP: dict[type[Any], list[Callable[..., str]]] = {
    ChartResult: [lambda result: result['meta']['symbol']],
    QuoteResult: [lambda result: result['symbol']],
    QuoteTypeResult: [lambda result: result['symbol']],
    RecommendationsFinanceResult: [lambda result: result['symbol']],
    InsightsFinanceResult: [lambda result: result['symbol']],
    OptionChainResult: [
        lambda result: result['underlyingSymbol'],
        lambda result: result['quote']['symbol'],
    ],
    RatingsResult: [
        lambda result: result['dir']['ticker'],
        lambda result: result['mm']['ticker'],
        lambda result: result['pt']['ticker'],
        lambda result: result['fin_score']['ticker'],
    ],
}
